Create django_develop.yml to realize CI in development server
gogixweb/clt-vs-pj pull request #18
Opened 2021-12-18 00:44 UTC by wlribeiro

2021-12-30 21:41 UTC, f3rn4nd0000 approved these changes

2022-01-06 22:35 UTC, ivancrneto requested changes

2022-01-06 22:35 UTC, ivancrneto commented on .github/workflows/django_develop.yml
> +        python-version: [3.9]
```suggestion
        python-version: ["3.10"]
```

2022-01-13 22:10 UTC, ivancrneto approved these changes

2022-01-13 22:10 UTC, merged