Button from index goes to contact page
gogixweb/clt-vs-pj pull request #20
Opened 2022-01-06 19:27 UTC by f3rn4nd0000

Add a button in index labeled 'Saiba mais sobre nós!' that goes to contact.html page

2022-01-06 22:37 UTC, ivancrneto requested changes

2022-01-06 22:37 UTC, ivancrneto commented on web/cltvspj/templates/cltvspj/contact.html
> +                        <a href="https://github.com/eduumach"><img class="mini-logo" src={% static "img/GitHub-Mark-64px.png" %}></a>
missing Eduardo's LinkedIn above

2022-01-09 23:56 UTC, wlribeiro approved these changes

2022-01-13 22:07 UTC, ivancrneto approved these changes

2022-01-13 22:07 UTC, merged